name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "Memulai Auto Deploy..."
            cd ~/solpos
            
            # Tarik kode terbaru dari GitHub
            git reset --hard
            git pull origin main
            
            # Setup Backend
            echo "Update Backend..."
            cd backend
            npm install
            npx prisma generate
            npx prisma db push
            
            # Setup Frontend
            echo "Update Frontend..."
            cd ../frontend
            npm install
            npm run build
            
            # Restart layanan dengan PM2
            echo "Restarting services..."
            pm2 restart solpos-backend
            
            echo "Auto Deploy Selesai!"
